### ISSUE TITLE
[実行時エラー] ウィンドウの任意のリサイズ Window::Resize() をすると灰色の画面のまま

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#13]
**エラーの内容 | Describe the runtime error**
Web 最新版、Windows + Google Chrome, ウィンドウの任意のリサイズ Window::Resize(1280, 720); をすると灰色の画面のままです。

**再現方法 | To Reproduce**
再現コード: https://gist.github.com/Reputeless/62de5ce914b8ba8f4e8b470c998b359c

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows  11
 - バージョン | Version: v0.6.4r0
 - GPU: GeForce RTX 3070
 - ブラウザ (Web 版) | Browser: Google Chrome

**備考 | Additional context**
他の環境では未検証です。

**Comment by nokotan** [comment]
Related: [Fix runtime exit while calling glfwSetWindowSize](https://github.com/emscripten-core/emscripten/pull/17376)

emscripten 側に glfwSetWindowSize 呼び出し中にランタイムが終了してしまう問題を確認できました。
暫定的な回避策はすでに実装できています。
