### ISSUE TITLE
モバイルデバイスにおいて、全画面化後の表示が不安定

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#15]
https://nokotan.github.io/OpenSiv3DForWeb-VSCode/ を実行して、右下の全画面化ボタンを押した結果

- Android + Chrome → 全画面表示できるが、画質が粗くなる（とくに Print の文字）
- iPad + Safari → 縦持ちのときは OK, 横持ちのときはレイアウトが乱れる
  - https://www.dropbox.com/s/2uke81s5pakkdms/IMG_0500.PNG?dl=0

**Comment by nokotan** [comment]
どちらが起きている現象でしょうか

- 横持ちのときは常にレイアウトが崩れる
- 横持ちにしたときにレイアウトが崩れる

**Comment by Reputeless** [comment]
横持ちのときは常にレイアウトが崩れる、です。

**Comment by nokotan** [comment]
**Android Chrome**

- フルスクリーンにしたときに、より小さい Viewport Size がブラウザによって割り当てられている現象が確認できました
- スマートな解消方法がなさそう (モバイルブラウザの仕様的な挙動のため)
- Related
  - [Unexpected Viewport width on fullscreen HTML5 on mobile browsers](https://github.com/libgdx/libgdx/issues/5340)
  - [Wrong fullscreen orientation and size on HTML5 projects on Android browsers](https://github.com/itchio/itch.io/issues/881)

**iOS(iPad) Safari**

- ブラウザ側が向きを無視した解像度 (Screen.width, height) を報告してくることが原因そうです
  - emscripten 側で対応すべきか、Siv3D Web Template 側で対応すべきかはもう少し考察の余地がありそう

**Comment by Reputeless** [comment]
動作が不安定なので、モバイルでは音量 +最大化バーを使わないのも手かもですね。

**Comment by nokotan** [comment]
追加の調査です

**Android Chrome**

- 非フルスクリーン時も解像度の横幅が割り当てられているわけではない
- viewport を固定値 (Window::Resize) にしてしまう？
  - Siv3D ライブラリ側と Siv3D Template は疎結合を保ちたいが、依存性が生じてしまう
  - デスクトップ環境への悪影響も要調査

**iPad Safari**

- 上から下へスライドするだけでフルスクリーンが解除されてしまうという予期しない動作もある (ブラウザの仕様で回避不可)

**iOS Safari**

- そもそもフルスクリーンにできない (ブラウザの仕様で回避不可)

**Comment by nokotan** [comment]
> 動作が不安定なので、モバイルでは音量 +最大化バーを使わないのも手かもですね。

モバイル環境では最大化をさせないという把握であっていますでしょうか。
iPad/iOS で最大化ボタンを使用できないこととし、グレーアウトさせるのはやるべきことと考えます

**Comment by Reputeless** [comment]
はい。不安定ならそもそも最大化を選択肢として提供せず、最大化バーで画面が狭くなることも回避したいです。。

**Comment by nokotan** [comment]
音量ボタンまで最初から提供しないことには同意できません。

ブラウザ側の制約で、最初のユーザ操作があるまでは音が出せないようになっています。まだ問題としては顕在化していませんが、最初から BGM を流すようなアプリだと、起動~最初のユーザ操作の間、無音になってしまいます。(回避不可)

アプリ側が音を出せない状況にあるということの表示がなければ、開発者/アプリユーザの両方が混乱しかねないため、少なくとも起動時は音量ボタンを表示する必要があると考えています。

最大化ボタンの代わりに、バーを隠すボタンを配置し、必要があれば画面を広くできるという仕様では要件は満たせないでしょうか。

**Comment by nokotan** [comment]
**Android Chrome**

原因解明です

- そもそも screen.width, screen.height が小さい値に設定されている
  - フルスクリーン時に emscripten がそれに合わせてリサイズしてしまう
  - High DPI 対応と同時に対応するのがよさそう

**Comment by nokotan** [comment]
**Android Chrome**

一旦 emscripten 側の canvas リサイズ機能を使わず、Siv3D Template で処理することにしてみました

> 最大化バーで画面が狭くなることも回避したいです。

コントロールバーの表示/非表示のこれ以上の議論は別の Issue でやりたいと考えています。(この Issue では Out of Scope な気がする)
