### ISSUE TITLE
TextBoxとTextEdit::activeが同期しない

### ISSUE THREAD

**Issue by Luke256** [nokotan/OpenSiv3D#26]
**予期しない動作の内容 | Describe the unexpected behavior**
SimpleGUI::TextBoxでTextEditStateのactiveがtrueでもボックスをユーザーがクリックしないと文字入力を受け付けない
(青く描画はされるがキーボードは反応しない)

**再現方法 | To Reproduce**
通常通りSimpleGUI::TextBoxでボックスを生成、常にactive=trueの状態にして起動

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: macOS
 - バージョン | Version: 10.15.7
 - GPU: Intel Iris Plus Graphics 1536 MB
 - ブラウザ (Web 版) | Browser: GoogleChrome

**発生環境(モバイルの場合) | Smartphone (please complete the following information):**
 - デバイス | Device:
 - OS:
 - バージョン | Version:
 - ブラウザ (Web 版) | Browser:

**備考 | Additional context**

**Comment by nokotan** [comment]
SimpleGUI::TextBox のアクティブ化は、ユーザのクリック時のみ有効になるように実装しています

しかし、Luke256 さんが期待する動作になるような実装は、Web 版およびブラウザ上では実装方法が存在しないため不可能[1] で、実装を変更するとしても、ユーザの入力が必ず必要な機能となります

[1]: テキスト入力の有効化のため、input 要素にフォーカスを与える処理を行う必要があるが、その関数の呼び出しはユーザ操作のコールバック関数上でしか許可されていないため

[ユーザーアクションが必要な機能](https://siv3d.kamenokosoft.com/ja/building/web-specific-notes#ユーザーアクションが必要な機能)
