### ISSUE TITLE
VS の Debug ビルドでアプリ実行時、ブラウザ画面上部にシーンに重なる赤いバーが表示される

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#27]
**予期しない動作の内容 | Describe the unexpected behavior**
VS の Debug ビルドでアプリ実行時、ブラウザ画面上部にシーンに重なる赤いバー:
![image](https://user-images.githubusercontent.com/3108136/188263727-f140809f-d81f-451b-8bca-97acb270578c.png)

コンソールに出力されるエラーメッセージ:
`mscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.`
![image](https://user-images.githubusercontent.com/3108136/188263722-fe791758-a78e-43e2-97b0-91ad05005a88.png)

**再現方法 | To Reproduce**
Visual Studio を使って Debug ビルドででデフォルトサンプルをビルド → 実行

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows 11
 - バージョン | Version: 0.6.5
 - ブラウザ (Web 版) | Browser: Google Chrome

**備考 | Additional context**
Release ビルドでは発生せず。

**Comment by nokotan** [comment]
emscripten の glfwSetInterval の実装ミスが原因ではありますが、フレームレート制御にこれを使っていないので、呼び出しを削除することで回避可能です

* glfwSetInterval は glfw のセットアップが終了していれば、エラーを出さないことが期待されている
* しかし、emscripten では glfwSetInterval が emscripten_set_main_loop  と emscripten_set_main_loop_timing に依存していて、emscripten_set_main_loop_timing は emscripten_set_main_loop を先に呼んでおかないとエラーとして取り扱われる

**Comment by nokotan** [comment]
そもそも "ブラウザ画面上部でシーンに重なる赤いバー" がエラー表示として妥当ではない/認識されていないようなので、別の表示方法の検討が必要と考えています
