### ISSUE TITLE
emscriptenのactivateの際、特定の引数を付けて実行すると環境変数が壊れる

### ISSUE THREAD

**Issue by mak1a** [nokotan/OpenSiv3D#3]
Windows(Power Shell)でemscriptenのactivateの際、
`emsdk activate 2.0.5-upstream --system`
と入力して実行すると、環境変数の
`C:\Windows\System32`
が消えてしまいます。多分--systemが悪さをしていると思いますが、一度検証していただけると助かります。(2.0.5-upstream以外でも検証していただけると幸いです。)

**Comment by nokotan** [comment]
関連: https://github.com/emscripten-core/emsdk/issues/634

(必要があれば再度Openしてください)
