### ISSUE TITLE
wasm-ld : error : unable to find library -lpng

### ISSUE THREAD

**Issue by 23tas9** [nokotan/OpenSiv3D#31]
**エラーの内容 | Describe the build error**

1>wasm-ld : error : unable to find library -lpng
1>emcc : error : 'C:/Users/tas9n/AppData/Local/Programs/Emscripten/upstream/bin\wasm-ld.exe -o C:/Users/tas9n/program/C++/OpenSiv3D/Web/OpenSiv3Dv0_6ForWeb1/Emscripten/Debug/OpenSiv3Dv0_6ForWeb1.wasm Emscripten/Debug/Main.o C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib\libSiv3DScript.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib\libSiv3D.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opencv\libopencv_objdetect.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opencv\libopencv_photo.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opencv\libopencv_imgproc.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opencv\libopencv_core.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/harfbuzz\libharfbuzz.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/freetype\libfreetype.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/turbojpeg\libturbojpeg.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/giflib\libgif.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/webp\libwebp.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opus\libopusfile.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opus\libopus.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/tiff\libtiff.a -lpng C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/zlib\libz.a C:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/SDL2\libSDL2.a -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/freetype -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/giflib -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/harfbuzz -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opencv -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/turbojpeg -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/webp -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/opus -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/tiff -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/libpng -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/zlib -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib/SDL2 -LC:/Users/tas9n/AppData/Local/Programs/OpenSiv3D(0.6.5)Web/lib -LC:\Users\tas9n\AppData\Local\Programs\Emscripten\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten C:\Users\tas9n\AppData\Local\Programs\Emscripten\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libvorbis.a C:\Users\tas9n\AppData\Local\Programs\Emscripten\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libogg.a -lGL-webgl2-full_es3 -lal -lhtml5 -lstubs-debug -lc-debug -ldlmalloc -lcompiler_rt -lc++ -lc++abi -lsockets -lwebgpu_cpp -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -emscripten-cxx-exceptions-allowed=InitSiv3D -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-if-defined=emscripten_stack_get_base --export-if-defined=emscripten_stack_get_end --export-if-defined=emscripten_stack_set_limits --export-if-defined=emscripten_stack_get_free --export-if-defined=emscripten_stack_init --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__wasm_call_ctors --export-if-defined=__errno_location --export-if-defined=getTempRet0 --export-if-defined=setTempRet0 --export-if-defined=__get_temp_ret --export-if-defined=__set_temp_ret --export-if-defined=__funcs_on_exit --export-if-defined=malloc --export-if-defined=free --export-if-defined=__cxa_is_pointer_type --export-if-defined=__cxa_can_catch --export-if-defined=setThrew --export-if-defined=ntohs --export-if-defined=htons --export-if-defined=__dl_seterr --export-if-defined=saveSetjmp --export-if-defined=emscripten_builtin_memalign --export-if-defined=memcpy --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (returned 1)
1>プロジェクト "OpenSiv3Dv0_6ForWeb1.vcxproj" のビルドが終了しました -- 失敗。

**再現方法 | To Reproduce**

公式サイト
https://siv3d.kamenokosoft.com/ja/building/overview
から手順通りEmscriptenのインストールからサンプルコードのビルドをしようとした際に以上のエラーが出ました。

**ビルド環境 | Develop environment (please complete the following information):**
 - OS: Windows 10 Home 21H2
 - 開発環境 | IDE: Visual Studio Community 2022 17.3.0

**備考 | Additional context**

**Comment by nokotan** [comment]
ご不便をおかけして申し訳ありません
[v0.6.5r2](https://github.com/nokotan/OpenSiv3D/releases/tag/v0.6.5r2) にて修正致しましたので、お手数をおかけしますが再度インストールするようにお願いいたします

**Comment by nokotan** [comment]
> (技術的な話題)
> 
> > wasm-ld : error : unable to find library -lpng
> 
> このエラーは、リンカが libpng.a の場所を見つけられないというものです。
> 
> Visual Studio プロジェクトテンプレートで、libpng.a に対するライブラリディレクトリを指定している項目があり、
> 一時的に間違ったディレクトリを指定していたコミットが、CI のビルド成果物のキャッシュ構成の間違いで v0.6.5.1 リリースに混入したことが原因でした。
