### ISSUE TITLE
SimpleHTTP::Get() / Post() サンプルで期待した結果が得られない

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#39]
**予期しない動作の内容 | Describe the unexpected behavior**
- reported by: https://discord.com/channels/443310697397354506/998714158621147237/1038378601646673980

Siv3D チュートリアルの GET サンプル / POST サンプルともに期待した正常な結果が得られない。

**再現方法 | To Reproduce**

- https://zenn.dev/reputeless/books/siv3d-documentation/viewer/tutorial-http#29.5-%EF%BC%88%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%EF%BC%89get-%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88
- https://zenn.dev/reputeless/books/siv3d-documentation/viewer/tutorial-http#29.5-%EF%BC%88%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%EF%BC%89get-%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows 11
 - バージョン | Version: v0.6.5r5
 - ブラウザ (Web 版) | Browser: Google Chrome

**備考**
ほかのプラットフォームでは発生せず

**Comment by nokotan** [comment]
"期待した正常な結果" とはどのような結果であるかもう少し詳細に教えていただけませんか

**Comment by Reputeless** [comment]
## 29.5 （サンプル）GET リクエスト
### コンソール出力

expected:
```
------
HTTP/1.1 200 OK
status code: 200
------
Date: Tue, 08 Nov 2022 02:45:01 GMT
Content-Type: application/json
Content-Length: 61
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
------
```

actual:
```
1251: [fail]    ❌ BinaryReader: Failed to open the file `/tmp/file`
------
HTTP/1.1 401 Unknown
status code: 401
------

------
```

### 画面表示

expected:
![20221108-114603-670](https://user-images.githubusercontent.com/3108136/200462742-4141003e-adfe-4916-8933-b449f0e66bde.png)

actual:
![20221108-114725-174](https://user-images.githubusercontent.com/3108136/200462891-d69c3b0d-acf6-4a54-93b9-d3703c5e178a.png)

## 29.6 （サンプル）POST リクエスト

### コンソール出力

expected:
```
------
HTTP/1.1 200 OK
status code: 200
------
Date: Tue, 08 Nov 2022 02:48:20 GMT
Content-Type: application/json
Content-Length: 492
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
------
```

actual:
```
```

### 画面表示

expected:
![image](https://user-images.githubusercontent.com/3108136/200463246-eb5122b8-7842-412e-8241-08ed452884b6.png)

actual:
![image](https://user-images.githubusercontent.com/3108136/200463422-32a56cc0-bc22-451e-93a6-3404ea606453.png)

**Comment by Reputeless** [comment]
関連する本体 Issue
- https://github.com/Siv3D/OpenSiv3D/issues/911
