### ISSUE TITLE
[v0.6] オーディオファイルのデコード結果が正しくない

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#4]
強化された Audio サンプルを実行したところ、
音声ファイルの長さや再生したときの再生スピードが実際と異なっていました。
デコード時や再生時のサンプリング周波数の設定がどこかで間違っている可能性があります。

分かりやすい再現方法:
- ~~`example/windmill.mp3`~~ `example/test.mp3` の `audio.lengthSec()` が実際よりも長い
- サンプリング周波数 22,050 Hz の Ogg ファイルを自前で用意してロードすると `audio.sampleRate()` で 44,100 Hz と表示されたり、実際の 2 倍速で再生されたりする

**Comment by nokotan** [comment]
> 
> - example/windmill.mp3 の audio.lengthSec() が実際よりも長い
>

example/test.mp3 でしょうか。
Safari, Chrome on macOS で 103秒 = 1分43秒と表示され、これは元ファイルの再生時間 (1分43秒) に一致しました。
Chrome on Windows では、112秒 = 1分52秒と表示され、元ファイルより音程が低く、すこし遅く再生されました。

>
> - サンプリング周波数 22,050 Hz の Ogg ファイルを自前で用意してロードすると audio.sampleRate() で 44,100 Hz と表示されたり、実際の 2 倍速で再生されたりする
>

手元の環境で再現しました。

Ogg のデコード処理は Siv3D 側の機能に任せていることを含めると、ブラウザ環境の問題というよりは、ファイルのサンプリングレートをどこかで無視してしまっていることが原因に思えます。

**Comment by nokotan** [comment]
途中で Wave オブジェクトをムーブ構築するところがあるのですが、Siv3D の実装上 ムーブ構築した Wave オブジェクトにサンプリングレートが引き継がれることは保証されてなかったりするのでしょうか。

**Comment by Reputeless** [comment]
！！
v0.6 の実装ミスで一部のコンストラクタでサンプリングレートが引き継がれていませんでした。
修正コミットを作成中です。またお手数をおかけしました。

**Comment by Reputeless** [comment]
修正しました。 https://github.com/Siv3D/OpenSiv3D/commit/9ca523acd83071603abe43766b609bdeb6456ee6
ムーブした先に引き継がれるのが正しい仕様です。

**Comment by nokotan** [comment]
Web版バイナリおよびサンプルアプリ更新しました

<https://github.com/nokotan/OpenSiv3D/actions/runs/928133900>
<https://siv3d-v6-apps.kamenokosoft.com>
