### ISSUE TITLE
特定のキーをpreventDefault()する機能

### ISSUE THREAD

**Issue by 23tas9** [nokotan/OpenSiv3D#40]
**追加する機能の内容 | Describe the solution you'd like**
指定したキーをpreventDefault()したい

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
Google Chromeには[機能のショートカット](https://support.google.com/chrome/answer/157179?hl=ja&co=GENIE.Platform%3DDesktop#zippy=)がありますが、ゲームでキーボード操作を実装する際にこれらの機能が邪魔になることがあります。

- 問題
WASDキーで移動、Ctrlキーでダッシュなどを実装する際、現在のページを保存するオプションが開かれゲームが中断される。

- 解決
Ctrlキー+SキーなどpreventDefault()できればこの問題が解決されます。

**Comment by nokotan** [comment]
**追加の考慮事項**
- TextInput に影響が伝搬しないようにする
- Siv3D ユーザにとって、あらゆるブラウザのショートカットがアプリの邪魔をしないというのが望まれた挙動という仮説
  - 無効化できないショートカットも存在するという既知の制約の追加の説明

**Comment by nokotan** [comment]
OpenSiv3D for Web の基幹的な部分の修正であるため、Siv3D 作者 (@Reputeless) にもレビューを依頼しました。

**Comment by Reputeless** [comment]
- `preventDefault()` は、個別のキーに設定できるのでしょうか
- C++ API 側から `preventDefault()` を制御することは技術的に可能ですか？ 

@nokotan 

可能なのであれば、文字列 / 定数など、何らかの引数を渡して、有効無効を切り替える Web 独自 API を検討してください。
デフォルトは現状と同じ（`preventDefault()` しない）で良いと思います。

**Comment by nokotan** [comment]
> - preventDefault() は、個別のキーに設定できるのでしょうか

if 文による条件分岐で呼ぶ/呼ばないの制御が可能です

> - C++ API 側から preventDefault() を制御することは技術的に可能ですか？

C++ API が何を指しているのかわかりませんが、C/C++ から (ビルド時にあらかじめ登録した) JavaScript の関数は自由に呼び出せます。

- Discord の質問の原文から、あらゆるブラウザのショートカットを無効にする手段も要望があるとみていましたが、実装を見送ります
- Siv3D の Input/InputGroup/InputCombination を引数に取る
- TextInput に影響が出る場合は、入力中は preventDefault を無効にする

**Comment by Reputeless** [comment]
では `s3d::Platform::Web::EnableKeyboardEvent(... , false);` 的な感じでよろしくお願いします。

「あらゆるブラウザのショートカットを無効にする」も `preventDefault()` を使う実装ですか？
そういうアプリがほかにもよくあるなら、 `s3d::Platform::Web::DisbaleKeyboardShortcuts();` を入れてもよさそうです。

**Comment by nokotan** [comment]
**追加の考慮事項**

- macOS での command キーの取り扱いをどうするか
- 抑制できないショートカットの取り扱い
  - タブを閉じる (command + W) はブラウザの制約上無効化できない (回避策なし)
  - 他にも無効化できないショートカットが存在しそう
    - リストアップのコストはかなり高い
