### ISSUE TITLE
見つからないファイル名が /tmp/file としてログに表示される

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#44]
再現コード
```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.6

void Main()
{
	const Texture texture{ U"example/windmill2.png" };

	while (System::Update())
	{
		
	}
}
```

expected:
```
319: [fail]    ❌ BinaryReader: Failed to open the file `example/windmill2.png`
```

actual:
```
319: [fail]    ❌ BinaryReader: Failed to open the file `/tmp/file`
```

**Comment by nokotan** [comment]
期待する出力も追加で情報提供をお願いします。

https://github.com/nokotan/OpenSiv3D/blob/v6_web_develop/Siv3D/src/Siv3D-Platform/Web/Siv3D/SimpleHTTP/SivSimpleHTTP.cpp#L128

SimpleHTTP を介する機能として、次のログフォーマットを考えていますが、Siv3D Studio ではユーザが予期しない URL として出力されてしまいます。

```
❌ SimpleHttp: Failed to get the url `https://...`
```

Siv3D Studio での表示例

```
OpenSiv3D for Web
1064: [fail]    ❌ SimpleHttp: Failed to get the url `https://memfs+.vscode-resource.vscode-cdn.net/siv3d-playground/example/windmill2.png`
```

**Comment by Reputeless** [comment]
最も期待する出力を追記しました。

なお、
`https://memfs+.vscode-resource.vscode-cdn.net/siv3d-playground/example/windmill2.png`
のような URL であっても、情報量が無いよりは好ましいと考えます。
`FileSystem::FileName()` の実装を流用することで URL 前半部分を削って `windmill2.png` のみにするのも良いと思います。

**Comment by nokotan** [comment]
出力の追記ありがとうございます。

> FileSystem::FileName() の実装を流用することで URL 前半部分を削って windmill2.png のみにするのも良いと思います。

SimpleHttp の Get/Post メソッド失敗時のエラーメッセージとして、完全な URL を表示したいので、申し訳ありませんが、この提案を却下させてください。
 
.html ファイルの URL の先頭部分とそれ以外のアセットの URL の先頭部分が一致するのであれば (
たとえば http://siv3d.jp/index.html から http://siv3d.jp/example/test.png をダウンロードする)、./example/test.png のような相対参照でアクセスできて、期待する動作を達成できます。

しかし、Siv3D Studio では、エクスプローラ上では同一フォルダにあっても、vscode の WebView の制約により .html ファイルの URL の先頭部分とそれ以外のアセットの URL の先頭部分が一致しないため、この手が使えません。

**Comment by nokotan** [comment]
Siv3D Studio で使っている、[参照する URL を .html ファイルのそれから .js ファイルのそれに切り替える部分](https://github.com/nokotan/OpenSiv3D/blob/v6_web_develop/Web/Siv3D.sharedMain.pre.js#L4) を流用して、期待する出力を達成できそうです。

```sh
OpenSiv3D for Web
1064: [fail]    ❌ SimpleHttp: Failed to get the url `example/windmill2.png`
```

また、この流用の副作用として、次のコードが有効になります。

```cpp
Texture texture { U"https://pbs.twimg.com/profile_images/741948418239537153/0ThD_LEf_reasonably_small.png" };
```
