### ISSUE TITLE
Windows で TextToSpeech が利用可能かどうかにかかわらず TextToSpeech unavailable という警告が出る

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#45]
再現方法:
Siv3D Studio でデフォルトのサンプルプログラムを実行
Windows 11 / Chrome

期待される動作:
警告が出ない

実際の動作: 
`⚠️ TextToSpeech unavailable` という警告が出力される

解決案:
① 警告が出ないよう実装を改善
② Web 版の TextToSpeech 機能を一旦無効化する

補足:
警告の出ない環境が見つからない。

**Comment by nokotan** [comment]
Issue 報告ありがとうございます。

当該機能は　OpenSiv3D for Web から削除するという方針を取らせていただきます。

[パッチ](https://github.com/nokotan/OpenSiv3D/commit/2bfc8c4dc552ab90da021ad636a4384efc0b1937) を作成しましたので、マージまでしばらくお待ちください。

**Comment by nokotan** [comment]
おそらく関連
https://stackoverflow.com/questions/21513706/getting-the-list-of-voices-in-speechsynthesis-web-speech-api

**Comment by nokotan** [comment]
> 期待される動作:
> 警告が出ない

実際に機能が利用できない場合は、警告が出るという動作を期待していると解釈させていただきます。

**Comment by nokotan** [comment]
> おそらく関連 https://stackoverflow.com/questions/21513706/getting-the-list-of-voices-in-speechsynthesis-web-speech-api

これを参考にして再度[パッチ](https://github.com/nokotan/OpenSiv3D/commit/1f29dc1060b44bdcdb2e1108f45e054c84cbaaa3)を作成しました。

依然として、ユーザーコードの開始前に利用可能な言語のリストアップが完了しない可能性が残りますが、TextToSpeech が利用可能かどうかにかかわらず TextToSpeech unavailable という警告が出るという挙動は改善されるはずです。
