### ISSUE TITLE
実行環境のキーボードの利用可否を取得したい

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#6]
キーボードが使えない実行環境で、Camera2D/3D の操作のためのミニ UI や、代替操作手法を提示するために、現在の実行環境を取得できる関数があると便利です。
どういう情報の取得が可能か意見を聞きたいです。それに基づいて API を提案します。

目標: v0.6.x

**Comment by nokotan** [comment]
モバイル/PC の識別が精一杯になりそうです

## 物理キーボードがあるかどうかの判定

不可能です. 該当するブラウザ API 自体が存在しません.

## 実行環境の判定

### User-Agent による判定

モバイル/タブレット/PC を識別する, 一番現実的な判定方法にはなります. ただ、User-Agent も deprecated になりつつあるので, 将来的には使えなくなる可能性はあります

### メディアクエリによる判定

レスポンシブ対応につかわれる方法で, おおよそ モバイル/PC を識別できます.
