### ISSUE TITLE
GLES3InternalTexture2D は depthTexture を持たないように

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#7]
related: https://github.com/Siv3D/OpenSiv3D/issues/648

- https://github.com/Siv3D/OpenSiv3D/commit/b08ddaa28977b00e9a1befa3857770de1256a76b

**Comment by nokotan** [comment]
<https://github.com/nokotan/OpenSiv3D/releases/tag/v0.6.0b3> で対応しました
