### ISSUE TITLE
GLFW エラーメッセージの改善

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3D#9]
- https://twitter.com/initial_nemui/status/1452098395699433474

GLFW の初期化に失敗するのは WebGL 2.0 非サポートの場合のみだと思われるので、エラーメッセージを具体的にする。例:「Your browser does not support WebGL 2.」

**Comment by nokotan** [comment]
Fixed in ba14b42f0e9a101e924b68eee3da2b38440f5ab0, thanks.
